import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App by Sumit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={roboto.className}>
        <nav>
          <ul className="flex gap-6 font-bold font text-3xl pb-6 justify-center">
            <li>
              <Link href="/">Home 1.57.00</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/blogs">Blogs</Link>
            </li>
            <li>
              <Link href="/posts">Posts</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer className="text-center text-5xl mt-10">Footer Area</footer>
      </body>
    </html>
  );
}
